# Travis CI script

language: c
compiler:
- gcc

# blocklist
branches:
  except:
    - gradle-removal
    - cmake-support

dist: bionic

env:
  - PURE_MAKE=yes BOARD=ml605 EXAMPLES=yes SYSTEM_INTEGRATION=no APP=halcsd
  - PURE_MAKE=yes BOARD=afcv3 EXAMPLES=yes SYSTEM_INTEGRATION=no APP=halcsd
  - PURE_MAKE=yes BOARD=afcv3_1 EXAMPLES=yes SYSTEM_INTEGRATION=no APP=halcsd

addons:
  apt:
    packages:
    - uuid-dev
    - graphviz
  sonarqube:
    organization: lnls-dig
    token:
      secure: "AXQyy5C9NUv1aeIeVuLClBtLDkZsR4MDTFpIkzgrZX5fOVtVjyukeXfxk91GOtR76lGS5aX0WZLz+yMxsjFcGb49wigPSArZ91VE/UUPMZEIenjzObFdlz23a4GcfBtzTqzlChLNj3AaD80Jt9jUWXlLxTg+1p3FjWmmPS4Nu/VmtL9Nk5XdUwWNnptWWgmf0oL1n9ACRtpEhlBWd8HqzgxfGcT+WPo99TqFm/RZkngSMfgy9u4n1EBixxT7xVe0YVx1pke9hKCpHBMypLuARide/ZAcUf9OeuSgRlpa2+cY/Fn1P6MNfPGIaDbCZQ7PjN8CSJFjsGq+WpT3kNEw96+FHGU4z43eih1Cgo4q6XfezVkk5eLq7QQQVPGDN72VIj2oBAvXoWLxqpY5mA95Nw/rWWahsRScYap+gMHIDGpEwd54RvUMbZSgYTxLc74x6VCMW71JwB0UwUPt9UczVvUQirvPP7JtS4Th0WbFMAXPdOJE0l2F5/mBHbJyWPfD9PA5R/EYIpVkEG5kaZeYcBi0yqIXhW+yAlL6oiPNM28b0RNRkg8bsM0JZL7Vz/+b7+4rU4Ac4b47pCRWgnK6CpWL4C8FY9i0hzAyGq4SCoZPUEHY+Q8zMaGWnqcUePGsk/5bIAtu/Ot7OZcdF9HU3Pg0yeqDyXuyP4sG2q5Er3I="
    branches:
      - master
      - devel
      - sonarqube-integration
      - sonarqube-gradle

before_install:
- git submodule update --init --recursive

install:
- pip install --user sphinx

#   Build and check this project
script:
- ./ci_build.sh
- ./ci_scanner.sh

# Generate and deploy documentation
after_success: "cd $TRAVIS_BUILD_DIR/doc && make html; cd $TRAVIS_BUILD_DIR"

cache:
  ccache: true
  directories:
    - '$HOME/.sonar/cache'

before_deploy:
- . ./ci_deploy.sh

deploy:
  - provider: releases
    api_key:
      secure: "ammPjSoAPm1RFwXJq2O4JSBHrtOlf/2LNtdB462IpCRek4p9EY/jFEoMhRnYlXWrRdYC0EAk/GSAtCLC7u22G66pACezg1Q0xJdfFSMwo7MWcU2ukSeRoFugw09OuB6E/LZ6NcDVYxXVhht/qqV4Em1N3H/rc+0qkEHUPg1YxjB/YIayuY+LsBQsXXiBBc0NVhNv3L1Lx7uKzvwPnsDtIDSbd8cLmWs3XiHnjbcshhZynHiV3I3eQD0hvCKQ3pK2TItcY7BPPGZbQI6UhVEsjcqDQov2sdw1VhVFSwqlPnpGvLJgvvMBDbdfQfMVdYui0eaSLB52+ZC3HyrQxAJotz43OAZEWzrShts548M2xZDklUhFRu9KovDC8pYNJU+pwumpela9pW3YSBroRwxtfEyeplCaaR0iT0rL9CdQBVRKhmwbVwPsUCKQ1/fngbFRJbSksFf6GXCiykbjkwkPXRdrwdZpff0sUjKmapH1iFBQIQ5k92k7qfd+MFoTgCKovpMWVMpYcBLGK0rxJIZy5gjvuJLX5NwGs+rdDO/oFVVDxXWldcaqDetFYhVZVVKkewdaTDDQb1Pr7FeP8iI6t+JwtsmVjFbrjBs5siN/YhHRzu6Jm0taL7NnktYEXKumlLS0Nn9sQWhKlC86R2pJGKF9+iuweIN1JBaw0y4ScHM="
    file_glob: true
    file: ${HALCS_DEPLOYMENT}
    skip_cleanup: true
    on:
      all_branches: true
      tags: true
      condition: $DEPLOY = "yes"

  - provider: pages
    skip-cleanup: true
    local-dir: doc/_build/html
    github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: false
    on:
      all_branches: true
